name: Terraform Apply to Production

# on:
#   pull_request:
#     paths: ['**.tf', '**.tfvars']
#   push:
#     branches: [main]

on:
  pull_request:
    paths:
          - 'infra/modules/**'
    branches: [main]
    types:
      - closed

env:
  AWS_REGION: eu-west-2

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:

  gate:
    name: Approval gate
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo "Waiting for approval from ${{ github.actor }} to apply Terraform…"

  tfapply-prod:
    needs: gate
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      # Installs Terraform on the GitHub runner
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      # Configures AWS access by using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@9dfa9aa010133d4807cd0272ad05d3fdb5b01340
        with:
          role-to-assume: arn:aws:iam::241661649258:role/github-actions-ecsv2
          role-session-name: tfapply-prod
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: ./infra/env/prod
        run: terraform init -input=false

      - name: Terraform Apply
        working-directory: ./infra/env/prod
        run: terraform apply -auto-approve -var-file prod.tfvars  